"""users table added

Revision ID: e24a5ac46f2e
Revises: 250d9ca9979c
Create Date: 2026-07-01 16:19:43.847919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e24a5ac46f2e'
down_revision: Union[str, Sequence[str], None] = '250d9ca9979c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_companies_email'), table_name='companies')
    op.drop_index(op.f('ix_companies_phone'), table_name='companies')
    op.create_unique_constraint(None, 'companies', ['email'])
    op.create_unique_constraint(None, 'companies', ['phone'])
    op.alter_column('jobs', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'companies', type_='unique')
    op.drop_constraint(None, 'companies', type_='unique')
    op.create_index(op.f('ix_companies_phone'), 'companies', ['phone'], unique=False)
    op.create_index(op.f('ix_companies_email'), 'companies', ['email'], unique=False)
    op.alter_column('companies', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
